/**
 * Anchor resolver for the PDF Overlay Precision skill.
 *
 * Reads assets/template-anchors.json (generated by `npm run extract-anchors`)
 * AND assets/template-regions.json (hand-authored) and resolves anchor-relative
 * coordinate refs into absolute (x, y) PDF points.
 *
 * Design philosophy: never hardcode coordinates. Every field on the ACORD 25
 * cert is positioned relative to a STATIC label that exists in the source
 * template's page content stream — labels like "INSURER A :", "EACH
 * OCCURRENCE", "CERTIFICATE NUMBER:", "WORKERS COMPENSATION" — OR a hand-
 * authored region (DATE_BOX, SIG_BOX, DESC_BOX, WC_OFFICER_BOX) for fields
 * with no nearby usable text. When ACORD revises the template, regenerating
 * the anchors JSON propagates the shift to every label-anchored field;
 * region anchors need a one-time manual update.
 *
 * Sides:
 *   right   x = anchor.x + anchor.width + dx,  y = anchor.y + dy
 *   left    x = anchor.x + dx,                 y = anchor.y + dy
 *   below   x = anchor.x + dx,                 y = anchor.y - LINE_HEIGHT + dy
 *   above   x = anchor.x + dx,                 y = anchor.y + LINE_HEIGHT + dy
 *   row     x = dx (absolute),                 y = anchor.y + dy
 *           Use `row` when x is dictated by table-column geometry (which lives
 *           in the rasterized PNG, not in label positions). The anchor still
 *           drives y so the field stays locked to its row's vertical
 *           position. Row label text shifts → field y shifts with it.
 *   inside  x = anchor.x + dx,                 y = anchor.y + dy
 *           For region anchors (rect boxes). dx/dy are offsets from the
 *           region's bottom-left. The no-overlap test asserts the resolved
 *           point falls inside the region's bounding box.
 */

import anchorsJson from '../assets/template-anchors.json' assert { type: 'json' };
import regionsJson from '../assets/template-regions.json' assert { type: 'json' };

export const LINE_HEIGHT = 12;

export type Side = 'right' | 'left' | 'below' | 'above' | 'row' | 'inside';

export interface AnchorRef {
  anchor: string;
  side: Side;
  dx: number;
  dy: number;
  /**
   * When the anchor text appears multiple times on the page (e.g., "EACH
   * OCCURRENCE" exists in both the GL row and the UMBRELLA row), set nearY
   * to the approximate target y to disambiguate. The resolver picks the
   * matching label whose y is closest to nearY.
   */
  nearY?: number;
}

export interface Label {
  text: string;
  x: number;
  y: number;
  width: number;
  height: number;
}

/**
 * A region anchor is a named rectangle. Used for fields whose position is
 * dictated by a drawn box (not a text label) — e.g., the DATE box in the
 * header, the Y/N officer-excluded box, the DESCRIPTION free-form area, and
 * the signature rectangle.
 *
 * For uniformity in the resolver, regions are exposed as Labels where
 * `text` = the region name. Looked up by exact, case-sensitive name match.
 */
export interface Region {
  name: string;
  x: number;
  y: number;
  width: number;
  height: number;
  comment?: string;
}

export class MissingAnchorError extends Error {
  constructor(
    public readonly searched: string,
    public readonly suggestions: string[],
  ) {
    super(
      `Anchor "${searched}" not found in assets/template-anchors.json or assets/template-regions.json. ` +
        `Did you mean one of: ${suggestions.map((s) => `"${s}"`).join(', ')}? ` +
        `Run \`npm run extract-anchors\` to regenerate if the template changed.`,
    );
    this.name = 'MissingAnchorError';
  }
}

function normalize(s: string): string {
  return s.trim().replace(/\s+/g, ' ').toLowerCase();
}

const labels: readonly Label[] = (anchorsJson as { labels: Label[] }).labels;
const regions: readonly Region[] = (regionsJson as { regions: Region[] }).regions;

const byNormText = new Map<string, Label[]>();
for (const l of labels) {
  const key = normalize(l.text);
  const list = byNormText.get(key);
  if (list) list.push(l);
  else byNormText.set(key, [l]);
}

const byRegionName = new Map<string, Label>();
for (const r of regions) {
  byRegionName.set(r.name, {
    text: r.name,
    x: r.x,
    y: r.y,
    width: r.width,
    height: r.height,
  });
}

function levenshtein(a: string, b: string): number {
  const m = a.length;
  const n = b.length;
  if (m === 0) return n;
  if (n === 0) return m;
  let prev: number[] = Array.from({ length: n + 1 }, (_, i) => i);
  let curr: number[] = new Array(n + 1).fill(0);
  for (let i = 1; i <= m; i++) {
    curr[0] = i;
    for (let j = 1; j <= n; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      const del = (prev[j] ?? 0) + 1;
      const ins = (curr[j - 1] ?? 0) + 1;
      const sub = (prev[j - 1] ?? 0) + cost;
      curr[j] = Math.min(del, ins, sub);
    }
    [prev, curr] = [curr, prev];
  }
  return prev[n] ?? 0;
}

export function findAnchor(text: string, nearY?: number): Label {
  // Region anchors win on exact name match (case-sensitive, no normalization).
  // Regions use UPPER_SNAKE_CASE names that can't collide with PDF text labels.
  const region = byRegionName.get(text);
  if (region) return region;

  const norm = normalize(text);
  const hits = byNormText.get(norm);
  if (hits && hits.length > 0) {
    if (nearY === undefined || hits.length === 1) return hits[0]!;
    return hits.reduce((best, l) =>
      Math.abs(l.y - nearY) < Math.abs(best.y - nearY) ? l : best,
    );
  }
  const candidates = [...labels.map((l) => l.text), ...regions.map((r) => r.name)];
  const suggestions = candidates
    .map((t) => ({ text: t, dist: levenshtein(norm, normalize(t)) }))
    .sort((a, b) => a.dist - b.dist)
    .slice(0, 3)
    .map((s) => s.text);
  throw new MissingAnchorError(text, suggestions);
}

export function resolveCoord(ref: AnchorRef): { x: number; y: number } {
  const a = findAnchor(ref.anchor, ref.nearY);
  switch (ref.side) {
    case 'right':
      return { x: a.x + a.width + ref.dx, y: a.y + ref.dy };
    case 'left':
      return { x: a.x + ref.dx, y: a.y + ref.dy };
    case 'below':
      return { x: a.x + ref.dx, y: a.y - LINE_HEIGHT + ref.dy };
    case 'above':
      return { x: a.x + ref.dx, y: a.y + LINE_HEIGHT + ref.dy };
    case 'row':
      return { x: ref.dx, y: a.y + ref.dy };
    case 'inside':
      return { x: a.x + ref.dx, y: a.y + ref.dy };
  }
}

export function listAnchors(): readonly Label[] {
  return labels;
}

export function listRegions(): readonly Region[] {
  return regions;
}

/**
 * True if the given anchor name resolves to a hand-authored region (rather
 * than an extracted text label). Used by the no-overlap test and cert-doctor
 * to apply the correct geometry check: regions are bounding boxes the field
 * must fall INSIDE, labels are bounding boxes the field must fall CLEAR OF.
 */
export function isRegionAnchor(name: string): boolean {
  return byRegionName.has(name);
}
