/**
 * Coordinate map for ACORD 25 (2016/03) field positions.
 *
 * Coordinate system: PDF points (72 per inch), origin at BOTTOM-LEFT.
 * Page size: US Letter = 612 × 792 points.
 *
 * Anchor-relative architecture (Phase 1.7, 2026-05-18):
 *
 *   Every drawn field declares a STATIC LABEL anchor + offset, not absolute
 *   coordinates. The resolver in lib/anchors.ts looks up the anchor's
 *   (x, y, width, height) from assets/template-anchors.json (regenerated by
 *   `npm run extract-anchors`) and computes the field's (x, y) at module load.
 *
 *   When ACORD ships a template revision that shifts a row, regenerating the
 *   anchors JSON propagates the shift to every field anchored to a moved
 *   label — no per-field coordinate retuning.
 *
 *   See .claude/skills/pdf-overlay-precision/SKILL.md for the workflow.
 *
 * Sides:
 *   right   value renders RIGHT of label, same baseline
 *   left    value renders LEFT of label, same baseline (rare; right-aligned)
 *   below   value renders one line BELOW label, same x-start
 *   above   value renders one line ABOVE label, same x-start
 *   row     value uses ANCHOR Y but ABSOLUTE x (for table column positions
 *           that aren't derivable from label positions). dx is interpreted
 *           as the absolute x coordinate.
 *   inside  value sits INSIDE a hand-authored region rect (DATE_BOX,
 *           WC_OFFICER_BOX, DESC_BOX, SIG_BOX). dx/dy are offsets from the
 *           region's bottom-left. Used for fields with no nearby text label.
 *
 * Phase 1.8 (2026-05-18): every field on the cert is now anchor-relative —
 * either to an extracted text label or a region anchor. There are no absolute
 * coordinate literals in this file. Cert-doctor enforces this.
 *
 * Tune with:   npm run calibrate   (writes out/calibration.pdf — red dots + anchor boxes)
 * Verify with: npm run regen-sheffer + visual diff against ~/Downloads/Sheffer COI (1).pdf
 * Regression:  tests/fillAcord25.positions.test.ts (locks each coord, no-overlap gate)
 */

import { z } from 'zod';
import { findAnchor, resolveCoord, type AnchorRef } from './anchors';

export const PAGE_WIDTH = 612;
export const PAGE_HEIGHT = 792;

export type Coord = { x: number; y: number; size?: number; maxWidth?: number };
export type RectCoord = { x: number; y: number; width: number; height: number };

export const DEFAULT_SIZE = 7.5;

function field(decl: AnchorRef & { size?: number; maxWidth?: number }): Coord {
  const { x, y } = resolveCoord(decl);
  const out: Coord = { x: round2(x), y: round2(y) };
  if (decl.size !== undefined) out.size = decl.size;
  if (decl.maxWidth !== undefined) out.maxWidth = decl.maxWidth;
  return out;
}

/**
 * Region-anchored rect: width and height come from the named region in
 * assets/template-regions.json; x/y come from the region's origin + (dx, dy).
 * Used for the signature rectangle so it inherits propagation discipline like
 * every other field — no hardcoded coordinates anywhere in this file.
 */
function rectFromRegion(name: string, opts: { dx?: number; dy?: number; width?: number; height?: number } = {}): RectCoord {
  const { dx = 0, dy = 0 } = opts;
  const a = findAnchor(name);
  return {
    x: round2(a.x + dx),
    y: round2(a.y + dy),
    width: opts.width ?? a.width,
    height: opts.height ?? a.height,
  };
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

/**
 * Field-level metadata used by the no-overlap regression test and cert-doctor.
 * Lists every anchor-relative field along with its anchor declaration.
 */
export const FIELD_ANCHORS: Record<string, AnchorRef> = {};

/**
 * Optional Zod validators for field values. Populated by declare() when a
 * `validate` schema is provided. fillAcord25 calls these before drawing to
 * catch malformed input (bad date format, out-of-enum value, etc.) at
 * render time rather than silently drawing garbage.
 */
export const FIELD_VALIDATORS: Record<string, z.ZodTypeAny> = {};

function declare<K extends string>(
  key: K,
  decl: AnchorRef & { size?: number; maxWidth?: number; validate?: z.ZodTypeAny },
): Coord {
  FIELD_ANCHORS[key] = {
    anchor: decl.anchor,
    side: decl.side,
    dx: decl.dx,
    dy: decl.dy,
    ...(decl.nearY !== undefined ? { nearY: decl.nearY } : {}),
  };
  if (decl.validate) {
    FIELD_VALIDATORS[key] = decl.validate;
  }
  return field(decl);
}

export const COORDS = {
  // ====================================================================
  // HEADER — date in the top-right box. Region-anchored to DATE_BOX.
  // ====================================================================
  DATE: declare('DATE', { anchor: 'DATE_BOX', side: 'inside', dx: 6, dy: 5, size: 8 }),

  // ====================================================================
  // PRODUCER block — anchor "PRODUCER" (top-left of producer cell)
  // ====================================================================
  PRODUCER_NAME:      declare('PRODUCER_NAME',      { anchor: 'PRODUCER', side: 'below', dx: 13.4, dy:  1.9, size: 7.5, maxWidth: 260 }),
  PRODUCER_ADDRESS_1: declare('PRODUCER_ADDRESS_1', { anchor: 'PRODUCER', side: 'below', dx: 13.4, dy: -7.1, size: 7.5, maxWidth: 260 }),
  PRODUCER_ADDRESS_2: declare('PRODUCER_ADDRESS_2', { anchor: 'PRODUCER', side: 'below', dx: 13.4, dy: -16.1, size: 7.5, maxWidth: 260 }),

  // ====================================================================
  // CONTACT column — each sub-row anchors to its own label
  // ====================================================================
  CONTACT_NAME:  declare('CONTACT_NAME',  { anchor: 'NAME:', side: 'right', dx: 15, dy: 0, size: 7.5, maxWidth: 220 }),
  CONTACT_PHONE: declare('CONTACT_PHONE', { anchor: 'PHONE', side: 'right', dx: 13, dy: 0, size: 7.5, maxWidth: 100 }),
  CONTACT_FAX:   declare('CONTACT_FAX',   { anchor: 'FAX',   side: 'right', dx:  4, dy: -0.6, size: 7.5, maxWidth: 75 }),
  CONTACT_EMAIL: declare('CONTACT_EMAIL', { anchor: 'E-MAIL', side: 'right', dx: 14, dy: 0, size: 7.5, maxWidth: 230 }),

  // ====================================================================
  // INSURERS block — anchored to each insurer's label
  // NAIC values use side="row" with absolute column x=572
  // ====================================================================
  INSURER_A_NAME: declare('INSURER_A_NAME', { anchor: 'INSURER A :', side: 'right', dx: 8, dy: 0, size: 7.5, maxWidth: 220 }),
  INSURER_A_NAIC: declare('INSURER_A_NAIC', { anchor: 'INSURER A :', side: 'row',   dx: 572, dy: 0, size: 7.5, maxWidth: 32 }),
  INSURER_B_NAME: declare('INSURER_B_NAME', { anchor: 'INSURER B :', side: 'right', dx: 8, dy: 0, size: 7.5, maxWidth: 220 }),
  INSURER_B_NAIC: declare('INSURER_B_NAIC', { anchor: 'INSURER B :', side: 'row',   dx: 572, dy: 0, size: 7.5, maxWidth: 32 }),
  INSURER_C_NAME: declare('INSURER_C_NAME', { anchor: 'INSURER C :', side: 'right', dx: 8, dy: 0, size: 7.5, maxWidth: 220 }),
  INSURER_C_NAIC: declare('INSURER_C_NAIC', { anchor: 'INSURER C :', side: 'row',   dx: 572, dy: 0, size: 7.5, maxWidth: 32 }),
  INSURER_D_NAME: declare('INSURER_D_NAME', { anchor: 'INSURER D :', side: 'right', dx: 8, dy: 0, size: 7.5, maxWidth: 220 }),
  INSURER_D_NAIC: declare('INSURER_D_NAIC', { anchor: 'INSURER D :', side: 'row',   dx: 572, dy: 0, size: 7.5, maxWidth: 32 }),
  INSURER_E_NAME: declare('INSURER_E_NAME', { anchor: 'INSURER E :', side: 'right', dx: 8, dy: 0, size: 7.5, maxWidth: 220 }),
  INSURER_E_NAIC: declare('INSURER_E_NAIC', { anchor: 'INSURER E :', side: 'row',   dx: 572, dy: 0, size: 7.5, maxWidth: 32 }),
  INSURER_F_NAME: declare('INSURER_F_NAME', { anchor: 'INSURER F :', side: 'right', dx: 8, dy: 0, size: 7.5, maxWidth: 220 }),
  INSURER_F_NAIC: declare('INSURER_F_NAIC', { anchor: 'INSURER F :', side: 'row',   dx: 572, dy: 0, size: 7.5, maxWidth: 32 }),

  // ====================================================================
  // INSURED block — anchored to "INSURED" label
  // ====================================================================
  INSURED_NAME:      declare('INSURED_NAME',      { anchor: 'INSURED', side: 'below', dx: 13.4, dy:  1.1, size: 7.5, maxWidth: 280 }),
  INSURED_ADDRESS_1: declare('INSURED_ADDRESS_1', { anchor: 'INSURED', side: 'below', dx: 13.4, dy: -10.9, size: 7.5, maxWidth: 280 }),
  INSURED_ADDRESS_2: declare('INSURED_ADDRESS_2', { anchor: 'INSURED', side: 'below', dx: 13.4, dy: -22.9, size: 7.5, maxWidth: 280 }),

  // ====================================================================
  // CERTIFICATE / REVISION NUMBER — anchored right of each label
  // dx=4 keeps clear of the label's colon (the PP-0009 fix)
  // ====================================================================
  CERT_NUMBER:     declare('CERT_NUMBER',     { anchor: 'CERTIFICATE NUMBER:', side: 'right', dx: 4, dy: 0, size: 7.5, maxWidth: 130 }),
  REVISION_NUMBER: declare('REVISION_NUMBER', { anchor: 'REVISION NUMBER:',    side: 'right', dx: 4, dy: 0, size: 7.5, maxWidth: 130 }),

  // ====================================================================
  // GL row — body fields use side="row" (x = absolute column, y = anchor)
  // Limits anchor to each limit-label individually
  // Checkboxes: X marks sit left of their labels (the form's checkbox glyphs).
  // ====================================================================
  GL_CHK_TYPE:           declare('GL_CHK_TYPE',         { anchor: 'COMMERCIAL GENERAL LIABILITY', side: 'left', dx: -11, dy: -0.5, size: 9 }),
  GL_CHK_OCCUR:          declare('GL_CHK_OCCUR',        { anchor: 'OCCUR',                        side: 'left', dx: -10, dy: -0.5, size: 9, nearY: 470 }),
  GL_CHK_AGG_POLICY:     declare('GL_CHK_AGG_POLICY',   { anchor: 'POLICY',                       side: 'left', dx: -11, dy: -0.5, size: 9, nearY: 422 }),
  GL_INSR_LTR:           declare('GL_INSR_LTR',      { anchor: 'COMMERCIAL GENERAL LIABILITY', side: 'row', dx:  28, dy: -6, size: 7.5 }),
  GL_POLICY_NUMBER:      declare('GL_POLICY_NUMBER', { anchor: 'COMMERCIAL GENERAL LIABILITY', side: 'row', dx: 223, dy: -6, size: 7.5, maxWidth: 92 }),
  GL_EFF_DATE:           declare('GL_EFF_DATE',      { anchor: 'COMMERCIAL GENERAL LIABILITY', side: 'row', dx: 322, dy: -6, size: 7.5 }),
  GL_EXP_DATE:           declare('GL_EXP_DATE',      { anchor: 'COMMERCIAL GENERAL LIABILITY', side: 'row', dx: 368, dy: -6, size: 7.5 }),
  GL_LIMIT_EACH_OCC:     declare('GL_LIMIT_EACH_OCC',     { anchor: 'EACH OCCURRENCE',         side: 'right', dx: 72.5, dy: 0, size: 7.5, maxWidth: 45, nearY: 482 }),
  GL_LIMIT_DAMAGE_RENT:  declare('GL_LIMIT_DAMAGE_RENT',  { anchor: 'DAMAGE TO RENTED',        side: 'right', dx: 71.4, dy: 0, size: 7.5, maxWidth: 45 }),
  GL_LIMIT_MED_EXP:      declare('GL_LIMIT_MED_EXP',      { anchor: 'MED EXP (Any one person)',side: 'right', dx: 58.9, dy: 0, size: 7.5, maxWidth: 45 }),
  GL_LIMIT_PERS_ADV_INJ: declare('GL_LIMIT_PERS_ADV_INJ', { anchor: 'PERSONAL & ADV INJURY',   side: 'right', dx: 58.2, dy: 0, size: 7.5, maxWidth: 45 }),
  GL_LIMIT_GEN_AGG:      declare('GL_LIMIT_GEN_AGG',      { anchor: 'GENERAL AGGREGATE',       side: 'right', dx: 65.4, dy: 0, size: 7.5, maxWidth: 45 }),
  GL_LIMIT_PROD_COMP_OP: declare('GL_LIMIT_PROD_COMP_OP', { anchor: 'PRODUCTS - COMP/OP AGG',  side: 'right', dx: 51.4, dy: 0, size: 7.5, maxWidth: 45 }),

  // ====================================================================
  // AUTO row
  // ====================================================================
  AUTO_INSR_LTR:          declare('AUTO_INSR_LTR',      { anchor: 'AUTOMOBILE LIABILITY', side: 'row', dx:  28, dy: -6, size: 7.5 }),
  AUTO_POLICY_NUMBER:     declare('AUTO_POLICY_NUMBER', { anchor: 'AUTOMOBILE LIABILITY', side: 'row', dx: 223, dy: -6, size: 7.5, maxWidth: 92 }),
  AUTO_EFF_DATE:          declare('AUTO_EFF_DATE',      { anchor: 'AUTOMOBILE LIABILITY', side: 'row', dx: 322, dy: -6, size: 7.5 }),
  AUTO_EXP_DATE:          declare('AUTO_EXP_DATE',      { anchor: 'AUTOMOBILE LIABILITY', side: 'row', dx: 368, dy: -6, size: 7.5 }),
  AUTO_LIMIT_CSL:         declare('AUTO_LIMIT_CSL',         { anchor: 'COMBINED SINGLE LIMIT',         side: 'right', dx: 60.8, dy: 0, size: 7.5, maxWidth: 45 }),
  AUTO_LIMIT_BI_PER_PERS: declare('AUTO_LIMIT_BI_PER_PERS', { anchor: 'BODILY INJURY (Per person)',    side: 'right', dx: 53.1, dy: 0, size: 7.5, maxWidth: 45 }),
  AUTO_LIMIT_BI_PER_ACC:  declare('AUTO_LIMIT_BI_PER_ACC',  { anchor: 'BODILY INJURY (Per accident)',  side: 'right', dx: 49.0, dy: 0, size: 7.5, maxWidth: 45 }),
  AUTO_LIMIT_PD:          declare('AUTO_LIMIT_PD',          { anchor: 'PROPERTY DAMAGE',               side: 'right', dx: 73.2, dy: 0, size: 7.5, maxWidth: 45 }),

  // ====================================================================
  // UMBRELLA row — EACH OCCURRENCE has a GL duplicate; use nearY to pin
  // ====================================================================
  UMB_INSR_LTR:       declare('UMB_INSR_LTR',      { anchor: 'UMBRELLA LIAB', side: 'row', dx:  28, dy: -6, size: 7.5 }),
  UMB_POLICY_NUMBER:  declare('UMB_POLICY_NUMBER', { anchor: 'UMBRELLA LIAB', side: 'row', dx: 223, dy: -6, size: 7.5, maxWidth: 92 }),
  UMB_EFF_DATE:       declare('UMB_EFF_DATE',      { anchor: 'UMBRELLA LIAB', side: 'row', dx: 322, dy: -6, size: 7.5 }),
  UMB_EXP_DATE:       declare('UMB_EXP_DATE',      { anchor: 'UMBRELLA LIAB', side: 'row', dx: 368, dy: -6, size: 7.5 }),
  UMB_LIMIT_EACH_OCC: declare('UMB_LIMIT_EACH_OCC',{ anchor: 'EACH OCCURRENCE', side: 'right', dx: 72.5, dy: 0, size: 7.5, maxWidth: 45, nearY: 338 }),
  UMB_LIMIT_AGG:      declare('UMB_LIMIT_AGG',     { anchor: 'AGGREGATE',       side: 'right', dx: 96.0, dy: 0, size: 7.5, maxWidth: 45 }),

  // ====================================================================
  // WC row — PER STATUTE checkbox + Y/N officer-excluded character
  // ====================================================================
  WC_CHK_PER_STATUTE:   declare('WC_CHK_PER_STATUTE', { anchor: 'PER', side: 'left', dx: -10, dy: -0.5, size: 9 }),
  WC_OFFICER_YN:        declare('WC_OFFICER_YN', { anchor: 'WC_OFFICER_BOX', side: 'inside', dx: 6, dy: 5, size: 8, validate: z.enum(['Y', 'N']) }),
  WC_INSR_LTR:          declare('WC_INSR_LTR',      { anchor: 'WORKERS COMPENSATION', side: 'row', dx:  28, dy: -9, size: 7.5 }),
  WC_POLICY_NUMBER:     declare('WC_POLICY_NUMBER', { anchor: 'WORKERS COMPENSATION', side: 'row', dx: 223, dy: -9, size: 7.5, maxWidth: 92 }),
  WC_EFF_DATE:          declare('WC_EFF_DATE',      { anchor: 'WORKERS COMPENSATION', side: 'row', dx: 322, dy: -9, size: 7.5 }),
  WC_EXP_DATE:          declare('WC_EXP_DATE',      { anchor: 'WORKERS COMPENSATION', side: 'row', dx: 368, dy: -9, size: 7.5 }),
  WC_LIMIT_EACH_ACC:    declare('WC_LIMIT_EACH_ACC',    { anchor: 'E.L. EACH ACCIDENT',       side: 'right', dx: 72.4, dy: 0, size: 7.5, maxWidth: 45 }),
  WC_LIMIT_DIS_EA_EMPL: declare('WC_LIMIT_DIS_EA_EMPL', { anchor: 'E.L. DISEASE - EA EMPLOYEE', side: 'right', dx: 47.7, dy: 0, size: 7.5, maxWidth: 45 }),
  WC_LIMIT_DIS_POL_LIM: declare('WC_LIMIT_DIS_POL_LIM', { anchor: 'E.L. DISEASE - POLICY LIMIT', side: 'right', dx: 51.1, dy: 0, size: 7.5, maxWidth: 45 }),

  // ====================================================================
  // OTHER row (bottom blank, below WC) — anchored to nearest WC limit label
  // The PP-0009 fix: OTHER_DESCRIPTION was at y=261 (above row body) — now
  // y=246 (inside row body). dy=-20 below the y=266 anchor.
  // ====================================================================
  OTHER_INSR_LTR:      declare('OTHER_INSR_LTR',      { anchor: 'E.L. DISEASE - POLICY LIMIT', side: 'row', dx:  28, dy: -26, size: 7.5 }),
  OTHER_DESCRIPTION:   declare('OTHER_DESCRIPTION',   { anchor: 'E.L. DISEASE - POLICY LIMIT', side: 'row', dx:  57, dy: -26, size: 7.5, maxWidth: 155 }),
  OTHER_POLICY_NUMBER: declare('OTHER_POLICY_NUMBER', { anchor: 'E.L. DISEASE - POLICY LIMIT', side: 'row', dx: 223, dy: -26, size: 7.5, maxWidth: 92 }),
  OTHER_EFF_DATE:      declare('OTHER_EFF_DATE',      { anchor: 'E.L. DISEASE - POLICY LIMIT', side: 'row', dx: 322, dy: -26, size: 7.5 }),
  OTHER_EXP_DATE:      declare('OTHER_EXP_DATE',      { anchor: 'E.L. DISEASE - POLICY LIMIT', side: 'row', dx: 368, dy: -26, size: 7.5 }),
  OTHER_LIMIT:         declare('OTHER_LIMIT',         { anchor: 'E.L. DISEASE - POLICY LIMIT', side: 'row', dx: 562, dy: -26, size: 7.5, maxWidth: 45 }),

  // ====================================================================
  // DESCRIPTION OF OPERATIONS — region-anchored to DESC_BOX. Text origin
  // sits near the top of the box (PDF y increases upward), so dy is the
  // height-ish offset from the region's bottom-left.
  // ====================================================================
  DESCRIPTION: declare('DESCRIPTION', { anchor: 'DESC_BOX', side: 'inside', dx: 5, dy: 67, size: 7, maxWidth: 540 }),

  // ====================================================================
  // CERTIFICATE HOLDER block — anchored to "CERTIFICATE HOLDER" label
  // ====================================================================
  HOLDER_NAME:      declare('HOLDER_NAME',      { anchor: 'CERTIFICATE HOLDER', side: 'below', dx: 13.4, dy: -7, size: 7.5, maxWidth: 290 }),
  HOLDER_ADDRESS_1: declare('HOLDER_ADDRESS_1', { anchor: 'CERTIFICATE HOLDER', side: 'below', dx: 13.4, dy: -19, size: 7.5, maxWidth: 290 }),
  HOLDER_ADDRESS_2: declare('HOLDER_ADDRESS_2', { anchor: 'CERTIFICATE HOLDER', side: 'below', dx: 13.4, dy: -31, size: 7.5, maxWidth: 290 }),

  // ====================================================================
  // Authorized Representative signature rectangle — region-anchored to
  // SIG_BOX. Inherits x/y/width/height directly from the region so a
  // template revision shifts the rect automatically.
  // ====================================================================
  SIGNATURE: rectFromRegion('SIG_BOX'),
} as const;

export type CoordKey = keyof typeof COORDS;
